#!/usr/bin/env bash
###############################################################################
# setup-credentials.sh — One-time setup wizard for HCS credentials
#
# This script:
#   1. Asks you for your HCS Access Key and Secret Key
#   2. Creates ~/.hcs-credentials.sh with the correct TF_VAR_ exports
#   3. Tells you exactly how to use it
#
# Only AK/SK are stored here. All other config (region, domain, endpoints)
# lives in terraform.tfvars per environment.
#
# USAGE:
#   ./scripts/setup-credentials.sh
###############################################################################

set -euo pipefail

# ─────────────────────────────────────────────────────────────────────────────
# Colours
# ─────────────────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
RESET='\033[0m'

log_info()    { echo -e "${BLUE}[INFO]${RESET}  $*"; }
log_success() { echo -e "${GREEN}[OK]${RESET}    $*"; }
log_warn()    { echo -e "${YELLOW}[WARN]${RESET}  $*"; }
log_error()   { echo -e "${RED}[ERROR]${RESET} $*" >&2; }
log_step()    { echo -e "\n${CYAN}${BOLD}▶ $*${RESET}"; }
log_divider() { echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"; }

CREDENTIALS_FILE="${HOME}/.hcs-credentials.sh"

# ─────────────────────────────────────────────────────────────────────────────
# Welcome
# ─────────────────────────────────────────────────────────────────────────────
clear
log_divider
echo ""
echo -e "  ${BOLD}HCS Credentials Setup Wizard${RESET}"
echo ""
echo "  This will create: ${CREDENTIALS_FILE}"
echo "  That file will NEVER be inside the git repository."
echo "  It lives in your home directory — only you can read it."
echo ""
echo "  Only your Access Key and Secret Key are stored here."
echo "  All other config (region, domain, endpoints) is in terraform.tfvars."
echo ""
log_divider
echo ""

# ─────────────────────────────────────────────────────────────────────────────
# Check if file already exists
# ─────────────────────────────────────────────────────────────────────────────
if [[ -f "$CREDENTIALS_FILE" ]]; then
  log_warn "Credentials file already exists: ${CREDENTIALS_FILE}"
  echo ""
  read -r -p "  Overwrite it? [y/N]: " overwrite
  if [[ "$overwrite" != "y" && "$overwrite" != "Y" ]]; then
    echo ""
    log_info "Keeping existing file. To load it, run:"
    echo -e "  ${YELLOW}source ~/.hcs-credentials.sh${RESET}"
    echo ""
    exit 0
  fi
  echo ""
fi

# ─────────────────────────────────────────────────────────────────────────────
# Collect HCS credentials
# ─────────────────────────────────────────────────────────────────────────────
log_step "Step 1 of 2 — HCS Access Key"
echo ""
echo "  Your Access Key (AK) is created in the HCS console under:"
echo "  My Credentials → Access Keys → Create Access Key"
echo "  It looks like a long alphanumeric string."
echo ""
read -r -p "  Enter your HCS Access Key (AK): " ACCESS_KEY
if [[ -z "$ACCESS_KEY" ]]; then
  log_error "Access Key cannot be empty."
  exit 1
fi

echo ""
log_step "Step 2 of 2 — HCS Secret Key"
echo ""
echo "  Your Secret Key (SK) is shown ONCE when you create the Access Key."
echo "  If you don't have it, create a new Access Key in the HCS console."
echo ""
# Use -s to hide input (like a password)
read -r -s -p "  Enter your HCS Secret Key (SK) [hidden]: " SECRET_KEY
echo ""  # newline after hidden input
if [[ -z "$SECRET_KEY" ]]; then
  log_error "Secret Key cannot be empty."
  exit 1
fi

# ─────────────────────────────────────────────────────────────────────────────
# Write credentials file
# ─────────────────────────────────────────────────────────────────────────────
log_step "Writing credentials file"

cat > "$CREDENTIALS_FILE" << EOF
#!/usr/bin/env bash
###############################################################################
# HCS Credentials — $(date '+%Y-%m-%d')
# Generated by: scripts/setup-credentials.sh
#
# USAGE:
#   source ~/.hcs-credentials.sh
#
# This file lives OUTSIDE the git repository.
# NEVER copy this into the repo. NEVER commit it.
# Permissions are set to 600 — only you can read it.
###############################################################################

# ── HCS Provider Credentials (Terraform reads TF_VAR_ prefixed vars) ─────────
export TF_VAR_access_key="${ACCESS_KEY}"
export TF_VAR_secret_key="${SECRET_KEY}"

# ── S3-Compatible Credentials (for Terraform OBS backend) ─────────────────────
# OBS uses S3-compatible APIs. Terraform's S3 backend reads these env vars.
export AWS_ACCESS_KEY_ID="${ACCESS_KEY}"
export AWS_SECRET_ACCESS_KEY="${SECRET_KEY}"

# ── Confirmation message ───────────────────────────────────────────────────────
echo "[HCS] Credentials loaded (AK: \${TF_VAR_access_key:0:4}****)"
EOF

# Lock down permissions — only owner can read or write
chmod 600 "$CREDENTIALS_FILE"

# ─────────────────────────────────────────────────────────────────────────────
# Verify it was written correctly
# ─────────────────────────────────────────────────────────────────────────────
if [[ ! -f "$CREDENTIALS_FILE" ]]; then
  log_error "Failed to write credentials file."
  exit 1
fi

echo ""
log_success "Credentials file created: ${CREDENTIALS_FILE}"
log_success "Permissions set to 600 (only you can read it)"

# ─────────────────────────────────────────────────────────────────────────────
# Test: source the file and verify exports
# ─────────────────────────────────────────────────────────────────────────────
log_step "Testing credentials file"
echo ""

# shellcheck disable=SC1090
source "$CREDENTIALS_FILE"

if [[ -n "${TF_VAR_access_key:-}" && -n "${TF_VAR_secret_key:-}" ]]; then
  log_success "Credentials sourced successfully"
  echo -e "  AK (masked): ${TF_VAR_access_key:0:4}****"
else
  log_error "Credentials did not load correctly. Check the file manually:"
  echo "  cat ${CREDENTIALS_FILE}"
  exit 1
fi

# ─────────────────────────────────────────────────────────────────────────────
# Done — print next steps
# ─────────────────────────────────────────────────────────────────────────────
echo ""
log_divider
echo ""
echo -e "  ${GREEN}${BOLD}Setup complete!${RESET}"
echo ""
echo -e "  ${BOLD}IMPORTANT — How to use your credentials:${RESET}"
echo ""
echo "  Every time you open a new terminal and want to run Terraform,"
echo "  you must load your credentials first by running:"
echo ""
echo -e "  ${YELLOW}    source ~/.hcs-credentials.sh${RESET}"
echo ""
echo "  You only type this ONCE per terminal session."
echo "  After that, all terraform commands in that session will work."
echo ""
echo -e "  ${BOLD}Optional — Auto-load on every terminal open:${RESET}"
echo ""
echo "  To avoid typing the source command every time, add it to your shell profile."
echo "  Run ONE of these depending on your shell:"
echo ""
echo -e "  ${YELLOW}    # For bash:${RESET}"
echo -e "  ${YELLOW}    echo 'source ~/.hcs-credentials.sh' >> ~/.bashrc${RESET}"
echo ""
echo -e "  ${YELLOW}    # For zsh:${RESET}"
echo -e "  ${YELLOW}    echo 'source ~/.hcs-credentials.sh' >> ~/.zshrc${RESET}"
echo ""
echo "  WARNING: Only do the above on YOUR personal machine."
echo "  Never auto-load credentials on a shared or CI machine."
echo ""
echo -e "  ${BOLD}Next steps to deploy:${RESET}"
echo ""
echo -e "  1. ${CYAN}source ~/.hcs-credentials.sh${RESET}"
echo -e "  2. ${CYAN}cd environments/dev${RESET}"
echo -e "  3. ${CYAN}cp terraform.tfvars.example terraform.tfvars${RESET}  then edit with your values"
echo -e "  4. ${CYAN}./scripts/tf.sh dev init${RESET}"
echo -e "  5. ${CYAN}./scripts/tf.sh dev plan${RESET}"
echo -e "  6. ${CYAN}./scripts/tf.sh dev apply${RESET}"
echo ""
log_divider
